######################################################################
# Automatically generated by qmake (3.0) V ápr. 14 16:05:16 2019
######################################################################

TEMPLATE = app
TARGET = sejtautomata_c++
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += sejtablak.h sejtszal.h
SOURCES += main.cpp sejtablak.cpp sejtszal.cpp
