######################################################################
# Automatically generated by qmake (3.0) V márc. 31 17:47:28 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
HEADERS += frakablak.h frakszal.h
SOURCES += frakablak.cpp frakszal.cpp main.cpp
